app:
  name: My App test
  description: Welcome to ${app.name}
  
my:
  greeting: Hello World
  list:
    values: One, Two, Three
    
db:
  connection: "{testConnectionString: 'http://__', userName: 'foo', password: 'pass'}"
  host: 127.0.0.1
  port: 2400